name: dataflow_stack
services:


  backend:
    container_name: dataflow_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
      - upload_data:/data
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - redis

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A config worker -l info --concurrency=4
    volumes:
      - ./backend:/app
      - upload_data:/data
    env_file: .env
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      API_TARGET: https://api-dataflow.pizani.ia.br
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5101:5101"
    depends_on:
      - backend

  redis:
    image: redis:latest
    restart: always


volumes:
  upload_data:
