name: dataflow_stack
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: dataflow
      POSTGRES_PASSWORD: dataflow
    volumes:
      - pgdataflow:/var/lib/postgresql/data
    ports:
      - "5401:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6401:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
      - upload_data:/data
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker -l info --concurrency=2
    volumes:
      - ./backend:/app
      - upload_data:/data
    env_file: .env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_TARGET: http://backend:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5101:5101"
    depends_on:
      - backend

volumes:
  pgdataflow:
  upload_data:
