# Generated by Django 5.1.4 on 2026-03-29 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('paused', 'Pausado'), ('error', 'Com Erro')], default='draft', max_length=20)),
                ('schedule_cron', models.CharField(blank=True, help_text="Expressão cron para execução agendada (ex: '0 */6 * * *')", max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações extras do pipeline (target schema, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('file_upload', 'Upload de Arquivo'), ('api_endpoint', 'Endpoint de API'), ('webhook', 'Webhook'), ('database', 'Banco de Dados')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Configuração da fonte (URL, headers, file_path, etc.)')),
                ('detected_schema', models.JSONField(blank=True, help_text='Schema detectado automaticamente pelo agente.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='dataflow.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rows_in', models.IntegerField(default=0)),
                ('rows_out', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('trigger', models.CharField(default='manual', help_text='O que disparou esta execução (manual, schedule, webhook).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dataflow.pipeline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('classify', 'Classificação de Schema'), ('quality', 'Análise de Qualidade'), ('plan', 'Planejamento de Transformação'), ('execute', 'Execução de Transformação'), ('validate', 'Validação Final')], max_length=20)),
                ('reasoning', models.TextField(help_text='Raciocínio do agente em linguagem natural.')),
                ('action', models.JSONField(help_text='Ação decidida pelo agente (tool call, transform, etc.).')),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='dataflow.processingrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('null_percentage', models.FloatField(default=0.0)),
                ('duplicate_percentage', models.FloatField(default=0.0)),
                ('schema_drift_detected', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0.0, help_text='Score de 0 a 100 atribuído pelo agente.')),
                ('details', models.JSONField(default=dict, help_text='Detalhes granulares por coluna.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='dataflow.processingrun')),
            ],
        ),
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('bronze', 'Bronze (Raw)'), ('silver', 'Silver (Clean)'), ('gold', 'Gold (Aggregated)')], max_length=10)),
                ('row_count', models.IntegerField(default=0)),
                ('schema', models.JSONField(default=dict, help_text='Colunas e tipos detectados.')),
                ('sample', models.JSONField(default=list, help_text='Primeiras 10 linhas como lista de dicts.')),
                ('stats', models.JSONField(default=dict, help_text='Estatísticas resumidas da camada.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='dataflow.processingrun')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('run', 'layer')},
            },
        ),
    ]
